import type { ActionName, Lang } from '../contracts'
import type { Step } from '../facetrack/calibrate'
import type { CameraProblem } from '../facetrack/camera'

type ToastText = Record<ActionName, (who: string) => string>

export const STRINGS = {
  en: {
    home: 'Home',
    connecting: 'Connecting to Clench…',
    speaking: 'Speaking…',
    finding: 'Finding options…',
    hint: 'Clench = send  |  B = cancel',
    pointing: {
      scanning: 'Scanning',
      headtilt: 'Head tilt is not ready yet: scanning',
      cameraOn: 'Camera on',
      noGaze: 'No eye tracker connected.',
      eyesLost: 'Eyes not detected',
    },
    camera: {
      denied: 'Camera blocked. Allow the camera for this page (camera icon in the address bar) and in Windows camera privacy settings.',
      none: 'No camera found. Plug in a webcam or turn the laptop camera on.',
      busy: 'The camera is in use by another app. Close Teams, Zoom or the Camera app.',
      insecure: 'The camera needs http://localhost (or https).',
      model: 'Face tracking could not start. Run npm --prefix web run assets, then reload.',
      error: 'The camera stopped working.',
      scanning: 'Scanning instead.',
      switch: 'Set Pointing mode to Auto or Scan.',
    } satisfies Record<CameraProblem | 'scanning' | 'switch', string>,
    calibrate: {
      ready: 'Head range: get ready',
      look: 'Look at the dot',
      steps: { center: 'Center', left: 'Left edge', right: 'Right edge', up: 'Top edge', down: 'Bottom edge' } satisfies Record<Step, string>,
      saving: 'Saving…',
      saved: 'Head range saved',
      noFace: (step: string) => `Could not see the face at "${step}". Face the camera and try again.`,
      tooSmall: { yaw: 'Turn a little further left and right, then try again.', pitch: 'Tilt a little further up and down, then try again.' },
      saveFailed: 'Could not save the head range (is the Core running?).',
      cameraOff: 'The camera is off. Set Pointing mode to Auto or Webcam first.',
      cancel: 'Esc = cancel',
    },
    confirm: {
      speak: 'Say this?',
      send_message: 'Send this message?',
      place_call: 'Place this call?',
      room_control: 'Do this?',
      help_alert: 'Call for help?',
      pull_over: 'Pull over here?',
      support: 'Call rider support?',
    } satisfies Record<ActionName, string>,
    help: {
      title: 'Calling for help',
      cancel: 'Double blink to cancel',
    },
    back: {
      menu: 'Go back?',
      confirm: 'Cancel this message?',
      how: 'Clench to confirm',
      stay: { menu: 'Do nothing to stay here', confirm: 'Do nothing to keep it' },
    },
    toast: {
      ok: {
        speak: () => 'Said',
        send_message: (who) => `Message sent to ${who}`,
        place_call: (who) => `Calling ${who}`,
        room_control: () => 'Done',
        help_alert: (who) => `Calling ${who}`,
        pull_over: () => 'Pulling over',
        support: () => 'Calling rider support',
      } satisfies ToastText,
      demo: {
        speak: () => '(demo mode) would say it',
        send_message: (who) => `(demo mode) would message ${who}`,
        place_call: (who) => `(demo mode) would call ${who}`,
        room_control: () => '(demo mode) would do it',
        help_alert: (who) => `(demo mode) would call ${who}`,
        pull_over: () => '(demo mode) would pull over',
        support: () => '(demo mode) would call rider support',
      } satisfies ToastText,
      failed: "Couldn't send",
    },
    setup: {
      brand: 'Your ride',
      setupProgress: 'Setup steps',
      calibrationProgress: 'Eye calibration',
      calibrationIn: (seconds: number) => `Calibration starts in ${seconds}s`,
      nextStep: 'Time until the next step',
      nextIn: (label: string, seconds: number) => `${label} in ${seconds}s · Continue sooner with a tap or double blink`,
      orbitHint: 'Look left or right to turn the view around your car. Calibration starts automatically; follow the dots when they appear.',
      previewUnavailable: 'The 3D car preview is available in the updated tablet app.',
      lookBlink: 'Look at an option, then double blink to choose',
      scanBlink: 'Options cycle automatically. Double blink when your eyes are detected, or tap to choose.',
      doneScanning: 'Setup is complete. Unavailable inputs stay off; scanning and touch are ready.',
      stepEyes: 'Eyes',
      stepBand: 'Headband',
      stepClench: 'Clench',
      welcomeTitle: "Let's get your ride ready",
      welcomeText: 'Two quick steps: we calibrate your eyes, then connect your headband and try one clench.',
      begin: 'Begin',
      eyesTitle: 'Your eyes',
      eyesText: 'Look at each dot until its ring fills. Keep your head still and comfortable.',
      eyesNone: 'Eye tracking is set up on the tablet. Here we go straight to the headband.',
      eyesStarting: 'Starting the eye tracker…',
      eyesError: "The eye tracker didn't start. You can skip this step.",
      eyesStart: 'Start',
      eyesFollow: 'Follow the dots…',
      tryAgain: 'Try again',
      next: 'Next',
      skip: 'Skip for now',
      bandTitle: 'Your headband',
      bandText: 'Turn the headband on and put it on. The pads behind your ears should touch skin.',
      bandLooking: 'Looking for your headband…',
      bandWaiting: 'Connected. Getting a steady signal…',
      bandContact: 'Adjust the band: a sensor is not touching your skin.',
      bandStill: 'Hold your head still for a moment.',
      bandGood: 'Signal looks good.',
      bandFailed: 'Could not connect.',
      noProfile: 'No saved headband profile on this device.',
      skipBand: 'Continue without the headband',
      clenchTitle: 'Try a clench',
      clenchText: 'Clench your jaw firmly once, then relax.',
      clenchWaiting: 'Waiting for your clench…',
      clenchWorked: 'That worked. Clench to choose, hold to call for help.',
      finish: 'Finish',
      doneTitle: "You're all set",
      doneText: 'Enjoy the ride.',
      go: 'Go',
    },
    trip: {
      speed: 'Speed',
      eta: 'Arrival',
      battery: 'Battery',
      temp: 'Cabin',
      windows: 'Windows',
      volume: 'Volume',
      windowShort: { front_left: 'FL', front_right: 'FR', rear_left: 'RL', rear_right: 'RR' },
      mph: 'mph',
      min: 'min',
      pullOver: 'Pull over here?',
      support: 'Call rider support?',
      layout: { car: 'Car', split: 'Split', map: 'Map' },
      destination: 'to destination',
      mapLabel: 'Route map',
      mapPreview: 'Map preview · live maps coming',
      confirm: 'Confirm',
      cancel: 'Cancel',
      how: 'Clench to confirm  |  Double blink to cancel',
      carHere: '3D car shows on the tablet',
    },
  },
  es: {
    home: 'Inicio',
    connecting: 'Conectando con Clench…',
    speaking: 'Hablando…',
    finding: 'Buscando opciones…',
    hint: 'Apretar = enviar  |  B = cancelar',
    pointing: {
      scanning: 'Escaneando',
      headtilt: 'Inclinar la cabeza aún no está listo: escaneando',
      cameraOn: 'Cámara encendida',
      noGaze: 'No hay seguimiento de ojos conectado.',
      eyesLost: 'No se detectan los ojos',
    },
    camera: {
      denied: 'Cámara bloqueada. Permite la cámara para esta página (ícono de cámara en la barra de direcciones) y en la privacidad de cámara de Windows.',
      none: 'No hay cámara. Conecta una webcam o enciende la cámara de la laptop.',
      busy: 'Otra aplicación está usando la cámara. Cierra Teams, Zoom o la app Cámara.',
      insecure: 'La cámara necesita http://localhost (o https).',
      model: 'El seguimiento de la cara no pudo iniciar. Ejecuta npm --prefix web run assets y recarga.',
      error: 'La cámara dejó de funcionar.',
      scanning: 'Escaneando en su lugar.',
      switch: 'Pon el modo de señalar en Auto o Escaneo.',
    } satisfies Record<CameraProblem | 'scanning' | 'switch', string>,
    calibrate: {
      ready: 'Rango de la cabeza: prepárate',
      look: 'Mira el punto',
      steps: { center: 'Centro', left: 'Borde izquierdo', right: 'Borde derecho', up: 'Borde de arriba', down: 'Borde de abajo' } satisfies Record<Step, string>,
      saving: 'Guardando…',
      saved: 'Rango de la cabeza guardado',
      noFace: (step: string) => `No se vio la cara en "${step}". Mira a la cámara e inténtalo de nuevo.`,
      tooSmall: { yaw: 'Gira un poco más a la izquierda y a la derecha e inténtalo de nuevo.', pitch: 'Inclina un poco más arriba y abajo e inténtalo de nuevo.' },
      saveFailed: 'No se pudo guardar el rango de la cabeza (¿está corriendo el Core?).',
      cameraOff: 'La cámara está apagada. Primero pon el modo de señalar en Auto o Webcam.',
      cancel: 'Esc = cancelar',
    },
    confirm: {
      speak: '¿Decir esto?',
      send_message: '¿Enviar este mensaje?',
      place_call: '¿Hacer esta llamada?',
      room_control: '¿Hacer esto?',
      help_alert: '¿Pedir ayuda?',
      pull_over: '¿Orillarse aquí?',
      support: '¿Llamar a soporte?',
    } satisfies Record<ActionName, string>,
    help: {
      title: 'Pidiendo ayuda',
      cancel: 'Parpadea dos veces para cancelar',
    },
    back: {
      menu: '¿Volver?',
      confirm: '¿Cancelar este mensaje?',
      how: 'Aprieta la mandíbula para confirmar',
      stay: { menu: 'No hagas nada para quedarte', confirm: 'No hagas nada para conservarlo' },
    },
    toast: {
      ok: {
        speak: () => 'Dicho',
        send_message: (who) => `Mensaje enviado a ${who}`,
        place_call: (who) => `Llamando a ${who}`,
        room_control: () => 'Hecho',
        help_alert: (who) => `Llamando a ${who}`,
        pull_over: () => 'Orillándose',
        support: () => 'Llamando a soporte',
      } satisfies ToastText,
      demo: {
        speak: () => '(modo demo) lo diría',
        send_message: (who) => `(modo demo) enviaría un mensaje a ${who}`,
        place_call: (who) => `(modo demo) llamaría a ${who}`,
        room_control: () => '(modo demo) lo haría',
        help_alert: (who) => `(modo demo) llamaría a ${who}`,
        pull_over: () => '(modo demo) se orillaría',
        support: () => '(modo demo) llamaría a soporte',
      } satisfies ToastText,
      failed: 'No se pudo enviar',
    },
    setup: {
      brand: 'Tu viaje',
      setupProgress: 'Pasos de configuración',
      calibrationProgress: 'Calibración de ojos',
      calibrationIn: (seconds: number) => `La calibración empieza en ${seconds}s`,
      nextStep: 'Tiempo hasta el siguiente paso',
      nextIn: (label: string, seconds: number) => `${label} en ${seconds}s · Toca o parpadea dos veces para avanzar antes`,
      orbitHint: 'Mira a la izquierda o derecha para girar la vista alrededor del auto. La calibración comienza sola; sigue los puntos cuando aparezcan.',
      previewUnavailable: 'La vista del auto 3D está disponible en la app actualizada de la tableta.',
      lookBlink: 'Mira una opción y parpadea dos veces para elegir',
      scanBlink: 'Las opciones cambian solas. Parpadea dos veces si se detectan tus ojos, o toca para elegir.',
      doneScanning: 'Configuración terminada. Las entradas no disponibles siguen apagadas; puedes usar el escaneo o tocar.',
      stepEyes: 'Ojos',
      stepBand: 'Diadema',
      stepClench: 'Apretar',
      welcomeTitle: 'Preparemos tu viaje',
      welcomeText: 'Dos pasos rápidos: calibramos tus ojos, luego conectamos tu diadema y probamos un apretón.',
      begin: 'Empezar',
      eyesTitle: 'Tus ojos',
      eyesText: 'Mira cada punto hasta que su anillo se llene. Mantén la cabeza quieta y cómoda.',
      eyesNone: 'El seguimiento de ojos se configura en la tableta. Pasamos directo a la diadema.',
      eyesStarting: 'Iniciando el seguimiento de ojos…',
      eyesError: 'El seguimiento de ojos no inició. Puedes saltar este paso.',
      eyesStart: 'Empezar',
      eyesFollow: 'Sigue los puntos…',
      tryAgain: 'Intentar de nuevo',
      next: 'Siguiente',
      skip: 'Saltar por ahora',
      bandTitle: 'Tu diadema',
      bandText: 'Enciende la diadema y póntela. Las almohadillas detrás de las orejas deben tocar la piel.',
      bandLooking: 'Buscando tu diadema…',
      bandWaiting: 'Conectada. Obteniendo una señal estable…',
      bandContact: 'Ajusta la diadema: un sensor no toca tu piel.',
      bandStill: 'Mantén la cabeza quieta un momento.',
      bandGood: 'La señal se ve bien.',
      bandFailed: 'No se pudo conectar.',
      noProfile: 'No hay un perfil de diadema guardado en este dispositivo.',
      skipBand: 'Continuar sin la diadema',
      clenchTitle: 'Prueba apretar',
      clenchText: 'Aprieta la mandíbula con firmeza una vez y relaja.',
      clenchWaiting: 'Esperando tu apretón…',
      clenchWorked: 'Funcionó. Aprieta para elegir, mantén para pedir ayuda.',
      finish: 'Terminar',
      doneTitle: 'Todo listo',
      doneText: 'Disfruta el viaje.',
      go: 'Ir',
    },
    trip: {
      speed: 'Velocidad',
      eta: 'Llegada',
      battery: 'Batería',
      temp: 'Cabina',
      windows: 'Ventanas',
      volume: 'Volumen',
      windowShort: { front_left: 'DI', front_right: 'DD', rear_left: 'TI', rear_right: 'TD' },
      mph: 'mph',
      min: 'min',
      pullOver: '¿Orillarse aquí?',
      support: '¿Llamar a soporte?',
      layout: { car: 'Auto', split: 'Dividido', map: 'Mapa' },
      destination: 'al destino',
      mapLabel: 'Mapa de la ruta',
      mapPreview: 'Vista previa · mapa en vivo pronto',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
      how: 'Aprieta para confirmar  |  Parpadea dos veces para cancelar',
      carHere: 'El auto 3D se ve en la tableta',
    },
  },
} satisfies Record<Lang, unknown>
