import type { ActionName, Lang } from '../contracts'
import type { Step } from '../facetrack/calibrate'
import type { CameraProblem } from '../facetrack/camera'

type ToastText = Record<ActionName, (who: string) => string>

export const STRINGS = {
  en: {
    home: 'Home',
    connecting: 'Connecting to Clench…',
    speaking: 'Speaking…',
    finding: 'Finding options…',
    hint: 'Clench = send  |  B = cancel',
    pointing: {
      scanning: 'Scanning',
      headtilt: 'Head tilt is not ready yet: scanning',
      cameraOn: 'Camera on',
      noGaze: 'No eye tracker connected. Set Pointing mode to Auto or Scan.',
      eyesLost: 'Eyes not detected',
    },
    camera: {
      denied: 'Camera blocked. Allow the camera for this page (camera icon in the address bar) and in Windows camera privacy settings.',
      none: 'No camera found. Plug in a webcam or turn the laptop camera on.',
      busy: 'The camera is in use by another app. Close Teams, Zoom or the Camera app.',
      insecure: 'The camera needs http://localhost (or https).',
      model: 'Face tracking could not start. Run npm --prefix web run assets, then reload.',
      error: 'The camera stopped working.',
      scanning: 'Scanning instead.',
      switch: 'Set Pointing mode to Auto or Scan.',
    } satisfies Record<CameraProblem | 'scanning' | 'switch', string>,
    calibrate: {
      ready: 'Head range: get ready',
      look: 'Look at the dot',
      steps: { center: 'Center', left: 'Left edge', right: 'Right edge', up: 'Top edge', down: 'Bottom edge' } satisfies Record<Step, string>,
      saving: 'Saving…',
      saved: 'Head range saved',
      noFace: (step: string) => `Could not see the face at "${step}". Face the camera and try again.`,
      tooSmall: { yaw: 'Turn a little further left and right, then try again.', pitch: 'Tilt a little further up and down, then try again.' },
      saveFailed: 'Could not save the head range (is the Core running?).',
      cameraOff: 'The camera is off. Set Pointing mode to Auto or Webcam first.',
      cancel: 'Esc = cancel',
    },
    confirm: {
      speak: 'Say this?',
      send_message: 'Send this message?',
      place_call: 'Place this call?',
      room_control: 'Do this?',
      help_alert: 'Call for help?',
      pull_over: 'Pull over here?',
      support: 'Call rider support?',
    } satisfies Record<ActionName, string>,
    help: {
      title: 'Calling for help',
      cancel: 'Double blink to cancel',
    },
    back: {
      menu: 'Go back?',
      confirm: 'Cancel this message?',
      how: 'Clench to confirm',
      stay: { menu: 'Do nothing to stay here', confirm: 'Do nothing to keep it' },
    },
    toast: {
      ok: {
        speak: () => 'Said',
        send_message: (who) => `Message sent to ${who}`,
        place_call: (who) => `Calling ${who}`,
        room_control: () => 'Done',
        help_alert: (who) => `Calling ${who}`,
        pull_over: () => 'Pulling over',
        support: () => 'Calling rider support',
      } satisfies ToastText,
      demo: {
        speak: () => '(demo mode) would say it',
        send_message: (who) => `(demo mode) would message ${who}`,
        place_call: (who) => `(demo mode) would call ${who}`,
        room_control: () => '(demo mode) would do it',
        help_alert: (who) => `(demo mode) would call ${who}`,
        pull_over: () => '(demo mode) would pull over',
        support: () => '(demo mode) would call rider support',
      } satisfies ToastText,
      failed: "Couldn't send",
    },
    trip: {
      speed: 'Speed',
      eta: 'Arrival',
      battery: 'Battery',
      temp: 'Cabin',
      windows: 'Windows',
      volume: 'Volume',
      windowShort: { front_left: 'FL', front_right: 'FR', rear_left: 'RL', rear_right: 'RR' },
      mph: 'mph',
      min: 'min',
      pullOver: 'Pull over here?',
      support: 'Call rider support?',
      confirm: 'Confirm',
      cancel: 'Cancel',
      how: 'Clench to confirm  |  Double blink to cancel',
      carHere: '3D car shows on the tablet',
    },
  },
  es: {
    home: 'Inicio',
    connecting: 'Conectando con Clench…',
    speaking: 'Hablando…',
    finding: 'Buscando opciones…',
    hint: 'Apretar = enviar  |  B = cancelar',
    pointing: {
      scanning: 'Escaneando',
      headtilt: 'Inclinar la cabeza aún no está listo: escaneando',
      cameraOn: 'Cámara encendida',
      noGaze: 'No hay seguimiento de ojos conectado. Pon el modo de señalar en Auto o Escaneo.',
      eyesLost: 'No se detectan los ojos',
    },
    camera: {
      denied: 'Cámara bloqueada. Permite la cámara para esta página (ícono de cámara en la barra de direcciones) y en la privacidad de cámara de Windows.',
      none: 'No hay cámara. Conecta una webcam o enciende la cámara de la laptop.',
      busy: 'Otra aplicación está usando la cámara. Cierra Teams, Zoom o la app Cámara.',
      insecure: 'La cámara necesita http://localhost (o https).',
      model: 'El seguimiento de la cara no pudo iniciar. Ejecuta npm --prefix web run assets y recarga.',
      error: 'La cámara dejó de funcionar.',
      scanning: 'Escaneando en su lugar.',
      switch: 'Pon el modo de señalar en Auto o Escaneo.',
    } satisfies Record<CameraProblem | 'scanning' | 'switch', string>,
    calibrate: {
      ready: 'Rango de la cabeza: prepárate',
      look: 'Mira el punto',
      steps: { center: 'Centro', left: 'Borde izquierdo', right: 'Borde derecho', up: 'Borde de arriba', down: 'Borde de abajo' } satisfies Record<Step, string>,
      saving: 'Guardando…',
      saved: 'Rango de la cabeza guardado',
      noFace: (step: string) => `No se vio la cara en "${step}". Mira a la cámara e inténtalo de nuevo.`,
      tooSmall: { yaw: 'Gira un poco más a la izquierda y a la derecha e inténtalo de nuevo.', pitch: 'Inclina un poco más arriba y abajo e inténtalo de nuevo.' },
      saveFailed: 'No se pudo guardar el rango de la cabeza (¿está corriendo el Core?).',
      cameraOff: 'La cámara está apagada. Primero pon el modo de señalar en Auto o Webcam.',
      cancel: 'Esc = cancelar',
    },
    confirm: {
      speak: '¿Decir esto?',
      send_message: '¿Enviar este mensaje?',
      place_call: '¿Hacer esta llamada?',
      room_control: '¿Hacer esto?',
      help_alert: '¿Pedir ayuda?',
      pull_over: '¿Orillarse aquí?',
      support: '¿Llamar a soporte?',
    } satisfies Record<ActionName, string>,
    help: {
      title: 'Pidiendo ayuda',
      cancel: 'Parpadea dos veces para cancelar',
    },
    back: {
      menu: '¿Volver?',
      confirm: '¿Cancelar este mensaje?',
      how: 'Aprieta la mandíbula para confirmar',
      stay: { menu: 'No hagas nada para quedarte', confirm: 'No hagas nada para conservarlo' },
    },
    toast: {
      ok: {
        speak: () => 'Dicho',
        send_message: (who) => `Mensaje enviado a ${who}`,
        place_call: (who) => `Llamando a ${who}`,
        room_control: () => 'Hecho',
        help_alert: (who) => `Llamando a ${who}`,
        pull_over: () => 'Orillándose',
        support: () => 'Llamando a soporte',
      } satisfies ToastText,
      demo: {
        speak: () => '(modo demo) lo diría',
        send_message: (who) => `(modo demo) enviaría un mensaje a ${who}`,
        place_call: (who) => `(modo demo) llamaría a ${who}`,
        room_control: () => '(modo demo) lo haría',
        help_alert: (who) => `(modo demo) llamaría a ${who}`,
        pull_over: () => '(modo demo) se orillaría',
        support: () => '(modo demo) llamaría a soporte',
      } satisfies ToastText,
      failed: 'No se pudo enviar',
    },
    trip: {
      speed: 'Velocidad',
      eta: 'Llegada',
      battery: 'Batería',
      temp: 'Cabina',
      windows: 'Ventanas',
      volume: 'Volumen',
      windowShort: { front_left: 'DI', front_right: 'DD', rear_left: 'TI', rear_right: 'TD' },
      mph: 'mph',
      min: 'min',
      pullOver: '¿Orillarse aquí?',
      support: '¿Llamar a soporte?',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
      how: 'Aprieta para confirmar  |  Parpadea dos veces para cancelar',
      carHere: 'El auto 3D se ve en la tableta',
    },
  },
} satisfies Record<Lang, unknown>
